apiVersion: v2
name: umbrella_chart
description: A Helm chart for Kubernetes
version: 1.0.0
appVersion: 1.0.0 
type: application
keywords:
  - Prometheus stack with Grafana
  - Redis DB
  - Redis exporter

dependencies:
  - name: kube-prometheus-stack 
    repository: https://prometheus-community.github.io/helm-charts
    version: 36.2.1
    condition: kube-prometheus-stack.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami 
    version: 16.13.1 
    condition: redis.enabled 
  - name: prometheus-redis-exporter
    repository: https://charts.bitnami.com/bitnami 
    repository: https://prometheus-community.github.io/helm-charts
    version: 5.0.0 
    condition: prometheus-redis-exporter.enabled 
